/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXNAMELEN 255

typedef char *nametype;
#ifdef __cplusplus
extern "C" bool_t xdr_nametype(XDR *, nametype*);
#elif __STDC__
extern  bool_t xdr_nametype(XDR *, nametype*);
#else /* Old Style C */
bool_t xdr_nametype();
#endif /* Old Style C */


typedef struct namenode *namelist;
#ifdef __cplusplus
extern "C" bool_t xdr_namelist(XDR *, namelist*);
#elif __STDC__
extern  bool_t xdr_namelist(XDR *, namelist*);
#else /* Old Style C */
bool_t xdr_namelist();
#endif /* Old Style C */


struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;
#ifdef __cplusplus
extern "C" bool_t xdr_namenode(XDR *, namenode*);
#elif __STDC__
extern  bool_t xdr_namenode(XDR *, namenode*);
#else /* Old Style C */
bool_t xdr_namenode();
#endif /* Old Style C */


struct readdir_res {
	int errno;
	union {
		namelist list;
	} readdir_res_u;
};
typedef struct readdir_res readdir_res;
#ifdef __cplusplus
extern "C" bool_t xdr_readdir_res(XDR *, readdir_res*);
#elif __STDC__
extern  bool_t xdr_readdir_res(XDR *, readdir_res*);
#else /* Old Style C */
bool_t xdr_readdir_res();
#endif /* Old Style C */


#define DIRPROG ((rpc_uint)0x20150976)
#define DIRVERS ((rpc_uint)1)

#ifdef __cplusplus
#define READDIR ((rpc_uint)1)
extern "C" readdir_res * readdir_1(nametype *, CLIENT *);
extern "C" readdir_res * readdir_1_svc(nametype *, struct svc_req *);

#elif __STDC__
#define READDIR ((rpc_uint)1)
extern  readdir_res * readdir_1(nametype *, CLIENT *);
extern  readdir_res * readdir_1_svc(nametype *, struct svc_req *);

#else /* Old Style C */
#define READDIR ((rpc_uint)1)
extern  readdir_res * readdir_1();
extern  readdir_res * readdir_1_svc();
#endif /* Old Style C */

#endif /* !_DIR_H_RPCGEN */
