/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <dirent.h>
#include <unistd.h>

readdir_res *
readdir_1_svc(nametype *argp, struct svc_req *rqstp)
{
	static readdir_res  result;
	namelist nl; namelist *nlp;
	DIR *dirp;
	struct dirent *d;
	xdr_free((xdrproc_t) xdr_readdir_res, (char*) &result);
	dirp= opendir(*argp);
	nlp = &result.readdir_res_u.list;

	sleep(5);

	while (d = readdir(dirp)) {
		nl = *nlp = malloc(sizeof(namenode));
		nl->name = strdup(d->d_name);
		nlp = &nl->next;
	}
	*nlp = NULL;
	/* Return the result */
	result.errno = 0;
	closedir(dirp);

	return(&result);
}
