/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"


void
dirprog_1( char* host )
{
	CLIENT *clnt;
	readdir_res  *result_1;
	nametype  readdir_1_arg;
	clnt = clnt_create(host, DIRPROG, DIRVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	namelist nl;
	char* dirname = "/Users/adrianbertschi/Documents/Work/Projects/ZHAW";
	result_1 = readdir_1(&dirname, clnt);
	if (result_1 == (readdir_res *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
	  for (nl = result_1->readdir_res_u.list;
	       nl != NULL;
	       nl = nl->next) {
	    printf("%s\n", nl->name);
	  }
	}

	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	dirprog_1( host );
}
