/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "versand.h"
#include <stdio.h> 

int *
placeorder_1_svc(order *argp, struct svc_req *rqstp)
{
  static int  result;

  FILE *file; 
  file = fopen("log.txt","a+");

  result = 0;
  int orderCount = 0;

  item *item;
  item = argp->first;
  fprintf(file,"\n Kunde: %d Adresse: %s",argp->customer_number, argp->adress);

  while (item != NULL) {
    orderCount++;
    fprintf(file,", Artikel: %u Menge: %d",item->item_number, item->count);
    result = 1;
    item = item->next;
  }

  fclose(file);

  return(&result);
}
