/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "versand.h"

bool_t
xdr_adress(XDR *xdrs, adress *objp)
{

	if (!xdr_string(xdrs, objp, MAXNAMELEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_itemlist(XDR *xdrs, itemlist *objp)
{

	if (!xdr_pointer(xdrs, (char **)objp, sizeof(struct item), (xdrproc_t)xdr_item))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_item(XDR *xdrs, item *objp)
{

	if (!xdr_int(xdrs, &objp->count))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->item_number))
		return (FALSE);
	if (!xdr_itemlist(xdrs, &objp->next))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_order(XDR *xdrs, order *objp)
{

	if (!xdr_adress(xdrs, &objp->adress))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->customer_number))
		return (FALSE);
	if (!xdr_itemlist(xdrs, &objp->first))
		return (FALSE);
	return (TRUE);
}
