/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VERSAND_H_RPCGEN
#define _VERSAND_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXNAMELEN 200

typedef char *adress;
#ifdef __cplusplus
extern "C" bool_t xdr_adress(XDR *, adress*);
#elif __STDC__
extern  bool_t xdr_adress(XDR *, adress*);
#else /* Old Style C */
bool_t xdr_adress();
#endif /* Old Style C */


typedef struct item *itemlist;
#ifdef __cplusplus
extern "C" bool_t xdr_itemlist(XDR *, itemlist*);
#elif __STDC__
extern  bool_t xdr_itemlist(XDR *, itemlist*);
#else /* Old Style C */
bool_t xdr_itemlist();
#endif /* Old Style C */


struct item {
	int count;
	u_int item_number;
	itemlist next;
};
typedef struct item item;
#ifdef __cplusplus
extern "C" bool_t xdr_item(XDR *, item*);
#elif __STDC__
extern  bool_t xdr_item(XDR *, item*);
#else /* Old Style C */
bool_t xdr_item();
#endif /* Old Style C */


struct order {
	adress adress;
	int customer_number;
	itemlist first;
};
typedef struct order order;
#ifdef __cplusplus
extern "C" bool_t xdr_order(XDR *, order*);
#elif __STDC__
extern  bool_t xdr_order(XDR *, order*);
#else /* Old Style C */
bool_t xdr_order();
#endif /* Old Style C */


#define ORDERPROG ((rpc_uint)0x20150976)
#define ORDERVERS ((rpc_uint)1)

#ifdef __cplusplus
#define PLACEORDER ((rpc_uint)1)
extern "C" int * placeorder_1(order *, CLIENT *);
extern "C" int * placeorder_1_svc(order *, struct svc_req *);

#elif __STDC__
#define PLACEORDER ((rpc_uint)1)
extern  int * placeorder_1(order *, CLIENT *);
extern  int * placeorder_1_svc(order *, struct svc_req *);

#else /* Old Style C */
#define PLACEORDER ((rpc_uint)1)
extern  int * placeorder_1();
extern  int * placeorder_1_svc();
#endif /* Old Style C */

#endif /* !_VERSAND_H_RPCGEN */
