/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "versand.h"
#include <stdio.h> 

int *
placeorder_1_svc(order *argp, struct svc_req *rqstp)
{
  static int  result;

  FILE *file; 
  file = fopen("log.txt","a+");
  result = 1; // Error by default

  if (file == NULL) {
    return(&result);
  }

  item *item;
  item = argp->first;
  fprintf(file,"\n Kunde: %d Adresse: %s",argp->customer_number, argp->adress);

  while (item != NULL) {
    fprintf(file,", Artikel: %u Menge: %d",item->item_number, item->count);
    result = 0; // No error if at least 1 article
    item = item->next;
  }

  fclose(file);

  return(&result);
}
