/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "versand.h"
#include <stdio.h> 
#include <time.h>


void
orderprog_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	order  placeorder_1_arg;
	clnt = clnt_create(host, ORDERPROG, ORDERVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	item item1;
	item1.count = 1;
	item1.item_number = 12345;

	item item2;
	item2.count = 2;
	item2.item_number = 67890;
	item1.next = &item2;
	item2.next = NULL;

	placeorder_1_arg.customer_number = 1234;
	placeorder_1_arg.adress = "Hauptrasse 12 9500 Wil";
	placeorder_1_arg.first = &item1;

	time_t now = time(NULL);

	int count = 0;
	while(difftime(time(NULL), now) < 1) {
		result_1 = placeorder_1(&placeorder_1_arg, clnt);
		count++;
	}
	printf("did it for: %d times\n", count);

	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	orderprog_1( host );
}
